site_name: Instant Repo 🍜
repo_url: https://github.com/niklasbaier/instant-repo
repo_name: instant-repo
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - tutorials.md
  - How to Guides: how-to-guides.md
  - reference.md
  - explanation.md
  - changelog.md
  - About:
      - The Author: author.md
      - Why this Project?: motivation.md
      - License: license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/niklasbaier
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/niklasbaier/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@niklas.baier

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://github.com/niklasbaier" target="_blank" rel="noopener">Niklas Baier</a>

plugins:
  - search
  - termynal
  - mkdocstrings
  - include-markdown:
      opening_tag: "[%"
      closing_tag: "%]"
